name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag corysanin/openrct2-discord-bridge:latest
    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin; docker push "corysanin/openrct2-discord-bridge:latest"
    
